In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 17 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 760 ms


NumPy ndarray 다차원 배열 객체

In [6]:
import numpy as np

In [7]:
data = np.random.randn(2, 3)

In [8]:
data

array([[-0.58701981,  0.49069432,  0.25073931],
       [-0.19992923, -1.21099524, -1.80458507]])

In [9]:
data * 10

array([[ -5.87019808,   4.9069432 ,   2.5073931 ],
       [ -1.99929226, -12.10995241, -18.04585071]])

In [10]:
data + data

array([[-1.17403962,  0.98138864,  0.50147862],
       [-0.39985845, -2.42199048, -3.60917014]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

ndarray 생성하기

In [13]:
data1 = [6, 7.5, 8, 0, 1]

In [14]:
arr1 = np.array(data1)

In [15]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [17]:
arr2 = np.array(data2)

In [18]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
arr2.ndim

2

In [20]:
arr2.shape

(2, 4)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int32')

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.empty((2, 3, 2))

array([[[8.30386082e-312, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [8.01097888e-307, 1.58817677e-052]],

       [[7.73900395e-091, 4.85407813e-033],
        [2.81192706e-033, 1.25870640e-047],
        [3.99910963e+252, 2.18569078e-312]]])

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [28]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [29]:
arr1.dtype

dtype('float64')

In [30]:
arr2.dtype

dtype('int32')

In [31]:
arr = np.array([1, 2, 3, 4, 5])

In [32]:
arr.dtype

dtype('int32')

In [33]:
float_arr = arr.astype(np.float64)

In [34]:
float_arr.dtype

dtype('float64')

In [35]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [36]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [37]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [38]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [39]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [40]:
int_array = np.arange(10)

In [41]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [42]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
empty_uint32 = np.empty(8, dtype='u4')

In [44]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

NumPy 배열의 산술 연산

In [45]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [46]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [48]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [50]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [51]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [52]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [53]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

색인과 슬라이싱 기초

In [54]:
arr = np.arange(10)

In [55]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr[5]

5

In [57]:
arr[5:8]

array([5, 6, 7])

In [58]:
arr[5:8] = 12

In [59]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [60]:
arr_slice = arr[5:8]

In [61]:
arr_slice

array([12, 12, 12])

In [62]:
arr_slice[1] = 12345

In [63]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [64]:
arr_slice[:] = 64

In [65]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [66]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [67]:
arr2d[2]

array([7, 8, 9])

In [68]:
arr2d[0][2]

3

In [69]:
arr2d[0, 2]

3

In [70]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [71]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
old_values = arr3d[0].copy()

In [74]:
arr3d[0] = 42

In [75]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [76]:
arr3d[0] = old_values

In [77]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
arr3d[1,0]

array([7, 8, 9])

In [79]:
x = arr3d[1]

In [80]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [81]:
x[0]

array([7, 8, 9])

슬라이스로 선택하기

In [82]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [83]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [84]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [87]:
arr2d[1, :2]

array([4, 5])

In [88]:
arr2d[:2, 2]

array([3, 6])

In [89]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [90]:
arr2d[:2, 1:] = 0

In [91]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

블리언값으로 선택하기

In [92]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [93]:
data = np.random.randn(7, 4)

In [94]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [95]:
data

array([[ 0.96258539,  0.36728087, -0.08474482, -2.74391282],
       [-0.25735099,  0.20077733,  1.26254003,  1.92946057],
       [ 1.92007258,  0.42658695, -0.215413  ,  1.4961395 ],
       [-1.1505174 , -1.0213616 ,  0.63378875,  0.43684925],
       [-0.45646334,  1.02708811,  1.30567972,  0.41282379],
       [-1.68688881,  0.84749035,  1.03183026, -0.46606402],
       [ 0.78187291, -0.58822207, -0.78543888, -0.13089791]])

In [96]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [97]:
data[names == 'Bob']

array([[ 0.96258539,  0.36728087, -0.08474482, -2.74391282],
       [-1.1505174 , -1.0213616 ,  0.63378875,  0.43684925]])

In [98]:
data[names == 'Bob', 2:]

array([[-0.08474482, -2.74391282],
       [ 0.63378875,  0.43684925]])

In [99]:
data[names == 'Bob', 3]

array([-2.74391282,  0.43684925])

In [100]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [101]:
data[~(names == 'Bob')]

array([[-0.25735099,  0.20077733,  1.26254003,  1.92946057],
       [ 1.92007258,  0.42658695, -0.215413  ,  1.4961395 ],
       [-0.45646334,  1.02708811,  1.30567972,  0.41282379],
       [-1.68688881,  0.84749035,  1.03183026, -0.46606402],
       [ 0.78187291, -0.58822207, -0.78543888, -0.13089791]])

In [102]:
cond = names == 'Bob'

In [103]:
data[~cond]

array([[-0.25735099,  0.20077733,  1.26254003,  1.92946057],
       [ 1.92007258,  0.42658695, -0.215413  ,  1.4961395 ],
       [-0.45646334,  1.02708811,  1.30567972,  0.41282379],
       [-1.68688881,  0.84749035,  1.03183026, -0.46606402],
       [ 0.78187291, -0.58822207, -0.78543888, -0.13089791]])

In [104]:
mask = (names == 'Bob') | (names == 'Will')

In [105]:
mask

array([ True, False,  True,  True,  True, False, False])

In [106]:
data[mask]

array([[ 0.96258539,  0.36728087, -0.08474482, -2.74391282],
       [ 1.92007258,  0.42658695, -0.215413  ,  1.4961395 ],
       [-1.1505174 , -1.0213616 ,  0.63378875,  0.43684925],
       [-0.45646334,  1.02708811,  1.30567972,  0.41282379]])

In [107]:
data[data < 0] = 0

In [108]:
data

array([[0.96258539, 0.36728087, 0.        , 0.        ],
       [0.        , 0.20077733, 1.26254003, 1.92946057],
       [1.92007258, 0.42658695, 0.        , 1.4961395 ],
       [0.        , 0.        , 0.63378875, 0.43684925],
       [0.        , 1.02708811, 1.30567972, 0.41282379],
       [0.        , 0.84749035, 1.03183026, 0.        ],
       [0.78187291, 0.        , 0.        , 0.        ]])

In [109]:
data[names != 'Joe'] = 7

In [110]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.20077733, 1.26254003, 1.92946057],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.84749035, 1.03183026, 0.        ],
       [0.78187291, 0.        , 0.        , 0.        ]])

팬시 색인

In [111]:
arr = np.empty((8, 4))

In [112]:
for i in range(8):
    arr[i] = i

In [113]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [114]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [115]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [116]:
arr = np.arange(32).reshape((8, 4))

In [117]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [118]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [119]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

배열 전치와 축 바꾸기

In [120]:
arr = np.arange(15).reshape((3, 5))

In [121]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [122]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [123]:
arr = np.random.rand(6, 3)

In [124]:
arr

array([[0.3644693 , 0.17628966, 0.13309943],
       [0.02917508, 0.0362144 , 0.08092122],
       [0.82433366, 0.03893127, 0.32679745],
       [0.69799552, 0.08947802, 0.09769495],
       [0.87329698, 0.2921773 , 0.29913839],
       [0.49310511, 0.3354868 , 0.73533226]])

In [125]:
np.dot(arr.T, arr)

array([[2.30621304, 0.58044414, 1.01228506],
       [0.58044414, 0.23983046, 0.38195447],
       [1.01228506, 0.38195447, 0.77080188]])

In [126]:
arr = np.arange(16).reshape((2, 2, 4))

In [127]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [128]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [129]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [130]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])